#!/bin/sh -eux

if [ $# -eq 1 ]; then
    if [ "$1" = "clean" ]; then
        git clean -dfX
        rm -rf common/term cross-detect freestanding-headers \
           stivale limine-efi libgcc-binaries \
           common-uefi-x86-64
        exit
    fi
fi

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -d common/term ] || git clone https://github.com/limine-bootloader/terminal.git common/term
[ -d cross-detect ] || git clone https://github.com/mintsuki/cross-detect.git
[ -d freestanding-headers ] || git clone https://github.com/mintsuki/freestanding-headers.git
[ -d stivale ] || git clone https://github.com/stivale/stivale.git
[ -d limine-efi ] || git clone https://github.com/limine-bootloader/limine-efi.git
[ -d libgcc-binaries ] || git clone https://github.com/mintsuki/libgcc-binaries.git

automake_libdir="$(automake --print-libdir)"

mkdir -p build-aux
cp "${automake_libdir}/install-sh" build-aux

autoreconf -fvi
